-- Agendamento pelo Cal.com dentro do funil do parceiro.
--
-- "agendou" passa a ser o desfecho bom da call fria: o lead escolheu dia e hora
-- no link do parceiro. Depois da reuniao o dono marca o desfecho real, que e o
-- que o parceiro enxerga no painel dele.
--
-- "autorizou" continua existindo para quem deixou a gente chamar no WhatsApp
-- mas nao marcou horario nenhum.
--
-- ATENCAO: nao existe migration runner neste projeto. O Dockerfile so builda e
-- roda o server. Este arquivo precisa ser aplicado na mao no Postgres do hub,
-- igual ao 002 e ao 003. Reexecutavel.

SET search_path TO groow, public;

/* ---------------------------------------------------------------- etapas */

ALTER TABLE groow."parceiro_leads" DROP CONSTRAINT IF EXISTS "ck_parceiro_leads_situacao";
ALTER TABLE groow."parceiro_leads" ADD CONSTRAINT "ck_parceiro_leads_situacao"
  CHECK ("situacao" IN (
    'a_ligar', 'nao_atendeu', 'ligou', 'vai_chamar', 'agendou', 'autorizou',
    'compareceu', 'nao_compareceu', 'fechou', 'nao_fechou', 'recusou'
  ));

/* ----------------------------------------------------------- agendamento */

ALTER TABLE groow."parceiro_leads"
  -- quando a reuniao esta marcada; vem do webhook do Cal
  ADD COLUMN IF NOT EXISTS "reuniao_em"     TIMESTAMPTZ,
  -- uid da reserva no Cal. E por ele que remarcacao e cancelamento acham o lead
  ADD COLUMN IF NOT EXISTS "cal_uid"        VARCHAR(64),
  -- link do Meet, para o dono abrir direto da fila de reunioes
  ADD COLUMN IF NOT EXISTS "reuniao_link"   VARCHAR(400),
  -- quando o dono marcou o desfecho. Distingue "ainda nao aconteceu" de
  -- "aconteceu e ninguem anotou".
  ADD COLUMN IF NOT EXISTS "desfecho_em"    TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "desfecho_nota"  VARCHAR(500),
  -- Respostas do diagnostico que o afiliado preenche durante a ligacao.
  -- JSONB e nao onze colunas: mudar as perguntas nao pode exigir migracao nova,
  -- porque aqui migracao e rodada na mao.
  ADD COLUMN IF NOT EXISTS "diagnostico"    JSONB;

-- Uma reserva do Cal aponta para um lead so. Sem isto, remarcar criaria linha
-- nova em vez de mover a hora da existente.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_pl_cal_uid"
  ON groow."parceiro_leads" ("cal_uid")
  WHERE "cal_uid" IS NOT NULL;

-- Fila de reunioes do dono: so quem tem horario marcado.
CREATE INDEX IF NOT EXISTS "ix_pl_reuniao"
  ON groow."parceiro_leads" ("reuniao_em")
  WHERE "reuniao_em" IS NOT NULL;

/* ------------------------------------------------ agendamentos sem dono */

-- Quem marca pelo site .com nao tem codigo de parceiro. Nao pode virar lead de
-- parceiro nenhum, mas tambem nao pode sumir: o dono precisa ver a reuniao.
--
-- Nome com prefixo cal_ de proposito: groow."agendamentos" ja existe, e do
-- GROOW antigo, exige lead_id e tem outro vocabulario de status. Sao coisas
-- diferentes e nao podem dividir a mesma tabela.
CREATE TABLE IF NOT EXISTS groow."cal_agendamentos" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cal_uid"      VARCHAR(64) NOT NULL,
  "nome"         VARCHAR(160) NOT NULL,
  "empresa"      VARCHAR(160),
  "telefone"     VARCHAR(32),
  "email"        VARCHAR(190),
  "cidade"       VARCHAR(120),
  "codigo"       VARCHAR(32),
  "parceiro_id"  INTEGER,
  "reuniao_em"   TIMESTAMPTZ NOT NULL,
  "reuniao_link" VARCHAR(400),
  "status"       TEXT NOT NULL DEFAULT 'marcada',
  "observacao"   TEXT,
  "payload"      JSONB,
  "criado_em"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "atualizado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_cal_agendamentos_status"
    CHECK ("status" IN ('marcada', 'remarcada', 'cancelada', 'compareceu', 'nao_compareceu')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_cal_agendamento_uid" UNIQUE ("cal_uid")
);

CREATE INDEX IF NOT EXISTS "ix_cal_agendamentos_quando"
  ON groow."cal_agendamentos" ("reuniao_em" DESC);
