-- Historico das buscas de prospeccao.
--
-- Antes disto o resultado vivia so no estado da tela: um F5 e a busca sumia
-- com o dinheiro ja gasto na API do Google. Agora cada busca fica gravada e
-- pode ser reaberta sem pagar de novo.
--
-- ATENCAO: nao existe migration runner. Aplicar na mao. Reexecutavel.

SET search_path TO groow, public;

CREATE TABLE IF NOT EXISTS groow."prospeccao_buscas" (
  "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  -- NULL = busca do dono. Preenchido = busca daquele parceiro.
  "parceiro_id" INTEGER,
  "nicho"       VARCHAR(120) NOT NULL,
  "cidade"      VARCHAR(120),
  "bairro"      VARCHAR(120),
  -- quando a busca foi por area no mapa
  "lat"         DOUBLE PRECISION,
  "lng"         DOUBLE PRECISION,
  "raio_km"     SMALLINT,
  "total"       INTEGER NOT NULL DEFAULT 0,
  -- as empresas como vieram, ja pontuadas. JSONB e nao tabela filha: isto e
  -- foto de um momento, nao entidade que se edita depois.
  "resultados"  JSONB NOT NULL DEFAULT '[]'::jsonb,
  "criado_em"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ix_prosp_buscas_dono"
  ON groow."prospeccao_buscas" ("parceiro_id", "criado_em" DESC);
