-- Schema do GROOW OS em Postgres. GERADO por db/converter-groow-pg.cjs.
-- Nao edite a mao: ajuste o conversor e rode de novo.
--
-- Vive no schema "groow" porque o public deste banco ja tem outra tabela leads
-- (a dos tenants do hub), sem nenhuma relacao com esta.

CREATE SCHEMA IF NOT EXISTS groow;
SET search_path TO groow, public;

-- Postgres nao tem ON UPDATE CURRENT_TIMESTAMP: precisa de trigger.
CREATE OR REPLACE FUNCTION groow.toca_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS groow."admin_perfil" (
  "id" INTEGER NOT NULL,
  "nome" VARCHAR(120) DEFAULT 'Admin',
  "email" VARCHAR(150),
  "foto" TEXT,
  "senha_hash" VARCHAR(255),
  "updated_at" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."agendamentos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lead_id" BIGINT NOT NULL,
  "data_hora" TIMESTAMPTZ NOT NULL,
  "tipo" TEXT NOT NULL DEFAULT 'diagnostico',
  "status" TEXT NOT NULL DEFAULT 'agendado',
  "notas" TEXT,
  "cal_event_id" VARCHAR(100),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_agendamentos_tipo" CHECK ("tipo" IN ('diagnostico', 'follow-up')),
  CONSTRAINT "ck_agendamentos_status" CHECK ("status" IN ('agendado', 'confirmado', 'no-show', 'realizado')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."blog_posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "slug" VARCHAR(180) NOT NULL,
  "titulo" VARCHAR(220) NOT NULL,
  "resumo" VARCHAR(320) NOT NULL DEFAULT '',
  "corpo" TEXT NOT NULL,
  "keyword_foco" VARCHAR(160) NOT NULL DEFAULT '',
  "categoria" VARCHAR(80) NOT NULL DEFAULT 'marketing-local',
  "status" TEXT NOT NULL DEFAULT 'rascunho',
  "origem" TEXT NOT NULL DEFAULT 'ia',
  "custo_usd" NUMERIC(8,4),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "published_at" TIMESTAMPTZ,
  CONSTRAINT "ck_blog_posts_status" CHECK ("status" IN ('rascunho', 'aprovado', 'publicado', 'arquivado')),
  CONSTRAINT "ck_blog_posts_origem" CHECK ("origem" IN ('ia', 'manual')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_blog_slug" UNIQUE ("slug")
);

CREATE TABLE IF NOT EXISTS groow."cardapio_respostas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cliente" VARCHAR(160) NOT NULL,
  "slug" VARCHAR(80),
  "total_itens" INTEGER NOT NULL DEFAULT 0,
  "selecionados" TEXT NOT NULL,
  "observacoes" TEXT,
  "lida" SMALLINT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."clientes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lead_id" BIGINT,
  "empresa" VARCHAR(150) NOT NULL,
  "responsavel" VARCHAR(120),
  "email" VARCHAR(150),
  "whatsapp" VARCHAR(30),
  "plano" VARCHAR(80),
  "valor_mensal" NUMERIC(10,2) NOT NULL DEFAULT 0,
  "valor_setup" NUMERIC(10,2) NOT NULL DEFAULT 0,
  "inicio_contrato" DATE,
  "fim_contrato" DATE,
  "status" TEXT NOT NULL DEFAULT 'ativo',
  "modulos" TEXT,
  "notas" TEXT,
  "progresso" SMALLINT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "parceiro_id" INTEGER,
  CONSTRAINT "ck_clientes_status" CHECK ("status" IN ('ativo', 'pausado', 'cancelado', 'concluido')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_clientes_lead" UNIQUE ("lead_id")
);

CREATE TABLE IF NOT EXISTS groow."follow_ups" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lead_id" BIGINT NOT NULL,
  "tipo" VARCHAR(30),
  "descricao" TEXT,
  "resultado" TEXT,
  "canal" TEXT NOT NULL,
  "mensagem" TEXT NOT NULL,
  "template_id" VARCHAR(80),
  "enviado_em" TIMESTAMPTZ,
  "abriu" SMALLINT NOT NULL DEFAULT 0,
  "respondeu" SMALLINT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_follow_ups_canal" CHECK ("canal" IN ('whatsapp', 'email')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."ia_base_conhecimento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "escopo" VARCHAR(64) NOT NULL DEFAULT 'default',
  "conteudo" TEXT,
  "atualizado_em" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_escopo" UNIQUE ("escopo")
);

CREATE TABLE IF NOT EXISTS groow."ia_followup_config" (
  "id" SMALLINT NOT NULL DEFAULT 1,
  "ativo" SMALLINT NOT NULL DEFAULT 0,
  "intervalos" VARCHAR(120) NOT NULL DEFAULT '4,12',
  "atualizado_em" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."ia_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "modulo" VARCHAR(40) NOT NULL,
  "acao" VARCHAR(160) NOT NULL DEFAULT '',
  "modelo" VARCHAR(60) NOT NULL DEFAULT '',
  "input_tokens" INTEGER NOT NULL DEFAULT 0,
  "output_tokens" INTEGER NOT NULL DEFAULT 0,
  "buscas_web" INTEGER NOT NULL DEFAULT 0,
  "custo_usd" NUMERIC(8,4) NOT NULL DEFAULT 0,
  "duracao_ms" INTEGER NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'ok',
  "detalhe" VARCHAR(300) NOT NULL DEFAULT '',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_ia_logs_status" CHECK ("status" IN ('ok', 'erro')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."leads" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" VARCHAR(150) NOT NULL,
  "email" VARCHAR(150),
  "telefone" VARCHAR(30),
  "empresa" VARCHAR(150),
  "setor" VARCHAR(80),
  "faturamento" VARCHAR(80),
  "cidade" VARCHAR(100),
  "origem" VARCHAR(60),
  "fonte_trafego" VARCHAR(40),
  "respostas" TEXT,
  "sonho" TEXT,
  "mensagem" TEXT,
  "notas" TEXT,
  "ultimo_contato_em" TIMESTAMPTZ,
  "status" TEXT NOT NULL DEFAULT 'novo',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "site" VARCHAR(255),
  "endereco" VARCHAR(255),
  "tem_site_proprio" SMALLINT,
  "place_id" VARCHAR(120),
  "parceiro_id" INTEGER,
  CONSTRAINT "ck_leads_status" CHECK ("status" IN ('novo', 'contatado', 'diagnostico', 'proposta', 'fechado', 'assinado', 'perdido', 'recusado', 'frio', 'quente')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."mapas_ecossistema" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" VARCHAR(200) NOT NULL,
  "dados" TEXT NOT NULL,
  "token" VARCHAR(48) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_mapa_token" UNIQUE ("token")
);

CREATE TABLE IF NOT EXISTS groow."mensagens_whatsapp" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lead_id" BIGINT NOT NULL,
  "direcao" TEXT NOT NULL,
  "conteudo" TEXT NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "processado_ia" SMALLINT NOT NULL DEFAULT 0,
  "intencao" VARCHAR(80),
  "evolution_msg_id" VARCHAR(120),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_mensagens_whatsapp_direcao" CHECK ("direcao" IN ('entrada', 'saida')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_mensagens_evolution_id" UNIQUE ("evolution_msg_id")
);

CREATE TABLE IF NOT EXISTS groow."metricas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cliente_id" BIGINT NOT NULL,
  "mes" CHAR(7) NOT NULL,
  "leads_captados" INTEGER NOT NULL DEFAULT 0,
  "agendamentos" INTEGER NOT NULL DEFAULT 0,
  "vendas" INTEGER NOT NULL DEFAULT 0,
  "faturamento_extra" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "no_shows" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_metricas_cliente_mes" UNIQUE ("cliente_id", "mes")
);

CREATE TABLE IF NOT EXISTS groow."parceiros" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" VARCHAR(160) NOT NULL,
  "email" VARCHAR(190) NOT NULL,
  "telefone" VARCHAR(32),
  "codigo" VARCHAR(32) NOT NULL,
  "senha_hash" VARCHAR(255),
  "comissao_setup_pct" NUMERIC(5,2) NOT NULL DEFAULT 0,
  "comissao_mensal_pct" NUMERIC(5,2) NOT NULL DEFAULT 0,
  "comissao_meses" INTEGER NOT NULL DEFAULT 12,
  "status" TEXT NOT NULL DEFAULT 'ativo',
  "observacao" TEXT,
  "criado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "atualizado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_parceiros_status" CHECK ("status" IN ('ativo', 'pausado')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_parceiro_email" UNIQUE ("email"),
  CONSTRAINT "uq_parceiro_codigo" UNIQUE ("codigo")
);

CREATE TABLE IF NOT EXISTS groow."parceiro_calls" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parceiro_id" INTEGER NOT NULL,
  "parceiro_lead_id" INTEGER,
  "transcricao" TEXT,
  "anotacao" TEXT,
  "resumo" TEXT,
  "duracao_seg" INTEGER NOT NULL DEFAULT 0,
  "criado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "atualizado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."parceiro_cliques" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parceiro_id" INTEGER NOT NULL,
  "destino" VARCHAR(20) NOT NULL DEFAULT 'pagina',
  "ip_hash" VARCHAR(64),
  "user_agent" VARCHAR(255),
  "referer" VARCHAR(255),
  "criado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."parceiro_comissoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parceiro_id" INTEGER NOT NULL,
  "cliente_id" INTEGER,
  "lead_id" INTEGER,
  "tipo" TEXT NOT NULL,
  "competencia" CHAR(7) NOT NULL,
  "base_valor" NUMERIC(10,2) NOT NULL DEFAULT 0,
  "percentual" NUMERIC(5,2) NOT NULL DEFAULT 0,
  "valor" NUMERIC(10,2) NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'previsto',
  "pago_em" DATE,
  "observacao" VARCHAR(255),
  "criado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_parceiro_comissoes_tipo" CHECK ("tipo" IN ('setup', 'recorrente', 'ajuste')),
  CONSTRAINT "ck_parceiro_comissoes_status" CHECK ("status" IN ('previsto', 'aprovado', 'pago', 'cancelado')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_comissao" UNIQUE ("parceiro_id", "cliente_id", "tipo", "competencia")
);

CREATE TABLE IF NOT EXISTS groow."parceiro_leads" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parceiro_id" INTEGER NOT NULL,
  "lead_id" INTEGER,
  "nome" VARCHAR(160) NOT NULL,
  "empresa" VARCHAR(160),
  "telefone" VARCHAR(32) NOT NULL,
  "email" VARCHAR(190),
  "cidade" VARCHAR(120),
  "setor" VARCHAR(120),
  "situacao" TEXT NOT NULL DEFAULT 'ligou',
  "optin" SMALLINT NOT NULL DEFAULT 0,
  "optin_em" TIMESTAMPTZ,
  "optin_origem" VARCHAR(40),
  "optin_prova" TEXT,
  "disparo_status" TEXT NOT NULL DEFAULT 'pendente',
  "disparo_em" TIMESTAMPTZ,
  "disparo_erro" VARCHAR(250),
  "observacao" TEXT,
  "criado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "atualizado_em" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_parceiro_leads_situacao" CHECK ("situacao" IN ('ligou', 'vai_chamar', 'autorizou', 'recusou')),
  CONSTRAINT "ck_parceiro_leads_disparo_status" CHECK ("disparo_status" IN ('pendente', 'enviado', 'falhou', 'respondeu')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_pl_tel" UNIQUE ("parceiro_id", "telefone")
);

CREATE TABLE IF NOT EXISTS groow."relatorios_cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cliente" VARCHAR(200) NOT NULL,
  "periodo" VARCHAR(20) NOT NULL,
  "dados" TEXT NOT NULL,
  "token" VARCHAR(48) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_rel_token" UNIQUE ("token")
);

CREATE TABLE IF NOT EXISTS groow."senhas_cofre" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cliente" VARCHAR(200) NOT NULL DEFAULT '',
  "servico" VARCHAR(200) NOT NULL,
  "url" VARCHAR(500) NOT NULL DEFAULT '',
  "usuario" VARCHAR(255) NOT NULL DEFAULT '',
  "segredo" TEXT NOT NULL,
  "notas" VARCHAR(500) NOT NULL DEFAULT '',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."social_conteudos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ideia_id" INTEGER,
  "tipo" TEXT NOT NULL,
  "titulo" VARCHAR(255) NOT NULL,
  "corpo" TEXT NOT NULL,
  "legenda" TEXT,
  "hashtags" VARCHAR(500),
  "custo_usd" NUMERIC(8,4),
  "status" TEXT NOT NULL DEFAULT 'rascunho',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_social_conteudos_tipo" CHECK ("tipo" IN ('reel', 'carrossel', 'story')),
  CONSTRAINT "ck_social_conteudos_status" CHECK ("status" IN ('rascunho', 'aprovado', 'publicado')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."social_ideias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pilar" VARCHAR(60) NOT NULL,
  "tipo" TEXT NOT NULL,
  "hook" VARCHAR(255) NOT NULL,
  "descricao" TEXT,
  "formato" VARCHAR(80) NOT NULL DEFAULT '',
  "status" TEXT NOT NULL DEFAULT 'nova',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_social_ideias_tipo" CHECK ("tipo" IN ('reel', 'carrossel', 'story')),
  CONSTRAINT "ck_social_ideias_status" CHECK ("status" IN ('nova', 'gerada', 'descartada')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."tarefas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "titulo" VARCHAR(200) NOT NULL,
  "prioridade" TEXT NOT NULL DEFAULT 'media',
  "status" TEXT NOT NULL DEFAULT 'pendente',
  "lead_id" BIGINT,
  "data_vencimento" DATE,
  "concluida_em" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "cliente_id" INTEGER,
  CONSTRAINT "ck_tarefas_prioridade" CHECK ("prioridade" IN ('alta', 'media', 'baixa')),
  CONSTRAINT "ck_tarefas_status" CHECK ("status" IN ('pendente', 'concluida')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."trafego_investimentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "canal" VARCHAR(40) NOT NULL,
  "mes" CHAR(7) NOT NULL,
  "valor" NUMERIC(10,2) NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_invest_canal_mes" UNIQUE ("canal", "mes")
);

CREATE TABLE IF NOT EXISTS groow."transacoes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cliente_id" BIGINT,
  "tipo" TEXT NOT NULL DEFAULT 'manual',
  "descricao" VARCHAR(200),
  "valor" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "data" DATE NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT "ck_transacoes_tipo" CHECK ("tipo" IN ('recorrente', 'setup', 'avulso', 'manual')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."utm_links" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" VARCHAR(160) NOT NULL,
  "url_final" TEXT NOT NULL,
  "utm_source" VARCHAR(80) NOT NULL,
  "utm_medium" VARCHAR(80) NOT NULL,
  "utm_campaign" VARCHAR(120) NOT NULL,
  "utm_content" VARCHAR(120),
  "utm_term" VARCHAR(120),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."wa_campanhas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" VARCHAR(160) NOT NULL,
  "template_nome" VARCHAR(160) NOT NULL,
  "template_idioma" VARCHAR(10) NOT NULL DEFAULT 'pt_BR',
  "body_params_modo" TEXT NOT NULL DEFAULT 'nenhum',
  "status" TEXT NOT NULL DEFAULT 'rascunho',
  "cap_dia" SMALLINT NOT NULL DEFAULT 100,
  "janela_inicio" SMALLINT NOT NULL DEFAULT 9,
  "janela_fim" SMALLINT NOT NULL DEFAULT 19,
  "pular_domingo" SMALLINT NOT NULL DEFAULT 1,
  "inicio_agendado" TIMESTAMPTZ,
  "optin_confirmado" SMALLINT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ck_wa_campanhas_body_params_modo" CHECK ("body_params_modo" IN ('nenhum', 'nome')),
  CONSTRAINT "ck_wa_campanhas_status" CHECK ("status" IN ('rascunho', 'agendada', 'enviando', 'pausada', 'concluida')),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS groow."wa_campanha_destinatarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "campanha_id" INTEGER NOT NULL,
  "whatsapp" VARCHAR(20) NOT NULL,
  "nome" VARCHAR(120),
  "status" TEXT NOT NULL DEFAULT 'pendente',
  "wamid" VARCHAR(128),
  "erro" VARCHAR(255),
  "enviado_em" TIMESTAMPTZ,
  CONSTRAINT "ck_wa_campanha_destinatarios_status" CHECK ("status" IN ('pendente', 'enviado', 'entregue', 'lido', 'respondeu', 'falha', 'optout')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_camp_zap" UNIQUE ("campanha_id", "whatsapp")
);

CREATE TABLE IF NOT EXISTS groow."wa_conversas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "canal" TEXT NOT NULL DEFAULT 'meta',
  "whatsapp" VARCHAR(32) NOT NULL,
  "nome" VARCHAR(120),
  "lead_id" INTEGER,
  "cliente_id" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'ai_active',
  "nao_lidas" INTEGER NOT NULL DEFAULT 0,
  "ultima_mensagem" TEXT,
  "ultima_mensagem_em" TIMESTAMPTZ,
  "handoff_em" TIMESTAMPTZ,
  "handoff_motivo" VARCHAR(120),
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "followups_enviados" INTEGER NOT NULL DEFAULT 0,
  "ultimo_followup_em" TIMESTAMPTZ,
  CONSTRAINT "ck_wa_conversas_canal" CHECK ("canal" IN ('meta', 'evolution')),
  CONSTRAINT "ck_wa_conversas_status" CHECK ("status" IN ('ai_active', 'handed_off', 'closed')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_canal_wa" UNIQUE ("canal", "whatsapp")
);

CREATE TABLE IF NOT EXISTS groow."wa_mensagens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "conversa_id" INTEGER NOT NULL,
  "origem" TEXT NOT NULL,
  "tipo" VARCHAR(24) NOT NULL DEFAULT 'text',
  "texto" TEXT,
  "wamid" VARCHAR(128),
  "status_entrega" TEXT,
  "metadata" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT "ck_wa_mensagens_origem" CHECK ("origem" IN ('user', 'ai', 'humano', 'sistema')),
  CONSTRAINT "ck_wa_mensagens_status_entrega" CHECK ("status_entrega" IN ('pending', 'sent', 'delivered', 'read', 'failed')),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_wamid" UNIQUE ("wamid")
);

CREATE TABLE IF NOT EXISTS groow."wa_optout" (
  "whatsapp" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("whatsapp")
);

-- indices
CREATE INDEX IF NOT EXISTS "agendamentos_idx_agendamentos_lead" ON groow."agendamentos" ("lead_id");
CREATE INDEX IF NOT EXISTS "agendamentos_idx_agendamentos_data_hora" ON groow."agendamentos" ("data_hora");
CREATE INDEX IF NOT EXISTS "agendamentos_idx_agendamentos_status" ON groow."agendamentos" ("status");
CREATE INDEX IF NOT EXISTS "agendamentos_idx_agendamentos_tipo" ON groow."agendamentos" ("tipo");
CREATE INDEX IF NOT EXISTS "blog_posts_idx_blog_status" ON groow."blog_posts" ("status", "published_at");
CREATE INDEX IF NOT EXISTS "clientes_idx_clientes_status" ON groow."clientes" ("status");
CREATE INDEX IF NOT EXISTS "clientes_idx_clientes_empresa" ON groow."clientes" ("empresa");
CREATE INDEX IF NOT EXISTS "follow_ups_idx_followups_lead" ON groow."follow_ups" ("lead_id");
CREATE INDEX IF NOT EXISTS "follow_ups_idx_followups_canal" ON groow."follow_ups" ("canal");
CREATE INDEX IF NOT EXISTS "follow_ups_idx_followups_enviado_em" ON groow."follow_ups" ("enviado_em");
CREATE INDEX IF NOT EXISTS "follow_ups_idx_followups_template" ON groow."follow_ups" ("template_id");
CREATE INDEX IF NOT EXISTS "ia_logs_idx_ia_data" ON groow."ia_logs" ("created_at");
CREATE INDEX IF NOT EXISTS "ia_logs_idx_ia_modulo" ON groow."ia_logs" ("modulo", "created_at");
CREATE INDEX IF NOT EXISTS "leads_idx_leads_email" ON groow."leads" ("email");
CREATE INDEX IF NOT EXISTS "leads_idx_leads_telefone" ON groow."leads" ("telefone");
CREATE INDEX IF NOT EXISTS "leads_idx_leads_status" ON groow."leads" ("status");
CREATE INDEX IF NOT EXISTS "leads_idx_leads_origem" ON groow."leads" ("origem");
CREATE INDEX IF NOT EXISTS "leads_idx_leads_created_at" ON groow."leads" ("created_at");
CREATE INDEX IF NOT EXISTS "leads_idx_leads_place" ON groow."leads" ("place_id");
CREATE INDEX IF NOT EXISTS "mensagens_whatsapp_idx_mensagens_lead" ON groow."mensagens_whatsapp" ("lead_id");
CREATE INDEX IF NOT EXISTS "mensagens_whatsapp_idx_mensagens_timestamp" ON groow."mensagens_whatsapp" ("timestamp");
CREATE INDEX IF NOT EXISTS "mensagens_whatsapp_idx_mensagens_processado" ON groow."mensagens_whatsapp" ("processado_ia");
CREATE INDEX IF NOT EXISTS "mensagens_whatsapp_idx_mensagens_direcao" ON groow."mensagens_whatsapp" ("direcao");
CREATE INDEX IF NOT EXISTS "metricas_idx_metricas_mes" ON groow."metricas" ("mes");
CREATE INDEX IF NOT EXISTS "parceiro_calls_ix_call_parceiro" ON groow."parceiro_calls" ("parceiro_id", "criado_em");
CREATE INDEX IF NOT EXISTS "parceiro_cliques_ix_clique_parceiro" ON groow."parceiro_cliques" ("parceiro_id", "criado_em");
CREATE INDEX IF NOT EXISTS "parceiro_comissoes_ix_comissao_parceiro" ON groow."parceiro_comissoes" ("parceiro_id", "competencia");
CREATE INDEX IF NOT EXISTS "parceiro_leads_ix_pl_situacao" ON groow."parceiro_leads" ("parceiro_id", "situacao");
CREATE INDEX IF NOT EXISTS "senhas_cofre_idx_cofre_cliente" ON groow."senhas_cofre" ("cliente");
CREATE INDEX IF NOT EXISTS "social_conteudos_idx_social_cont_status" ON groow."social_conteudos" ("status");
CREATE INDEX IF NOT EXISTS "social_conteudos_fk_social_cont_ideia" ON groow."social_conteudos" ("ideia_id");
CREATE INDEX IF NOT EXISTS "social_ideias_idx_social_ideias_status" ON groow."social_ideias" ("status", "pilar");
CREATE INDEX IF NOT EXISTS "transacoes_idx_transacoes_data" ON groow."transacoes" ("data");
CREATE INDEX IF NOT EXISTS "transacoes_idx_transacoes_cliente" ON groow."transacoes" ("cliente_id");
CREATE INDEX IF NOT EXISTS "wa_campanhas_idx_wa_camp_status" ON groow."wa_campanhas" ("status");
CREATE INDEX IF NOT EXISTS "wa_campanha_destinatarios_idx_dest_wamid" ON groow."wa_campanha_destinatarios" ("wamid");
CREATE INDEX IF NOT EXISTS "wa_campanha_destinatarios_idx_dest_camp_status" ON groow."wa_campanha_destinatarios" ("campanha_id", "status");
CREATE INDEX IF NOT EXISTS "wa_conversas_idx_ultima" ON groow."wa_conversas" ("ultima_mensagem_em");
CREATE INDEX IF NOT EXISTS "wa_mensagens_idx_conversa" ON groow."wa_mensagens" ("conversa_id", "created_at");

-- triggers de updated_at
DROP TRIGGER IF EXISTS "tg_admin_perfil_updated" ON groow."admin_perfil";
CREATE TRIGGER "tg_admin_perfil_updated" BEFORE UPDATE ON groow."admin_perfil"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_agendamentos_updated" ON groow."agendamentos";
CREATE TRIGGER "tg_agendamentos_updated" BEFORE UPDATE ON groow."agendamentos"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_blog_posts_updated" ON groow."blog_posts";
CREATE TRIGGER "tg_blog_posts_updated" BEFORE UPDATE ON groow."blog_posts"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_clientes_updated" ON groow."clientes";
CREATE TRIGGER "tg_clientes_updated" BEFORE UPDATE ON groow."clientes"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_leads_updated" ON groow."leads";
CREATE TRIGGER "tg_leads_updated" BEFORE UPDATE ON groow."leads"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_mapas_ecossistema_updated" ON groow."mapas_ecossistema";
CREATE TRIGGER "tg_mapas_ecossistema_updated" BEFORE UPDATE ON groow."mapas_ecossistema"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_relatorios_cliente_updated" ON groow."relatorios_cliente";
CREATE TRIGGER "tg_relatorios_cliente_updated" BEFORE UPDATE ON groow."relatorios_cliente"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_senhas_cofre_updated" ON groow."senhas_cofre";
CREATE TRIGGER "tg_senhas_cofre_updated" BEFORE UPDATE ON groow."senhas_cofre"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_tarefas_updated" ON groow."tarefas";
CREATE TRIGGER "tg_tarefas_updated" BEFORE UPDATE ON groow."tarefas"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_trafego_investimentos_updated" ON groow."trafego_investimentos";
CREATE TRIGGER "tg_trafego_investimentos_updated" BEFORE UPDATE ON groow."trafego_investimentos"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

DROP TRIGGER IF EXISTS "tg_wa_campanhas_updated" ON groow."wa_campanhas";
CREATE TRIGGER "tg_wa_campanhas_updated" BEFORE UPDATE ON groow."wa_campanhas"
  FOR EACH ROW EXECUTE FUNCTION groow.toca_updated_at();

-- ---------------------------------------------------------------------------
-- prospeccao_emails: não existia no MySQL de origem (era criada em runtime pela
-- rota /api/admin/prospeccao/email). Convertida à mão junto com o resto.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS groow."prospeccao_emails" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome_empresa" VARCHAR(255) NOT NULL DEFAULT '',
  "email" VARCHAR(255) NOT NULL,
  "assunto" VARCHAR(255) NOT NULL DEFAULT '',
  "campanha" VARCHAR(255) NOT NULL DEFAULT '',
  "status" TEXT NOT NULL DEFAULT 'enviado',
  "erro" VARCHAR(500),
  "resend_id" VARCHAR(80),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "ck_prospeccao_emails_status" CHECK ("status" IN ('enviado','erro'))
);
CREATE INDEX IF NOT EXISTS "prospeccao_emails_idx_pe_email"
  ON groow."prospeccao_emails" ("email", "created_at");
